package com.itemstore.location.country.sweden;

import java.util.EnumSet;

public enum City {

    ALINGSAS("Alingsas",EnumSet.noneOf(District.class)),
    ARBOGA("Arboga",EnumSet.noneOf(District.class)),
            Arvika("Arvika",EnumSet.noneOf(District.class)),
    Askersund("Askersund",EnumSet.noneOf(District.class)),
            Avaskar("Avaskar",EnumSet.noneOf(District.class)),
    Avesta("Avesta",EnumSet.noneOf(District.class)),
            Boden("Boden",EnumSet.noneOf(District.class)),
    Bollnas("Bollnäs",EnumSet.noneOf(District.class)),
            Borgholm("Borgholm",EnumSet.noneOf(District.class)),
    Borlange("Borlange",EnumSet.noneOf(District.class)),
            Boras("Boras",EnumSet.noneOf(District.class)),
    Broo("Broo",EnumSet.noneOf(District.class)),
            Bratte("Bratte",EnumSet.noneOf(District.class)),
    Bastad("Bastad",EnumSet.noneOf(District.class)),
            Djursholm("Djursholm",EnumSet.noneOf(District.class)),
    Eksjo("Eksjö",EnumSet.noneOf(District.class)),
            Elleholm("Elleholm",EnumSet.noneOf(District.class)),
    Enkoping("Enkoping",EnumSet.noneOf(District.class)),
            Eskilstuna("Eskilstuna",EnumSet.noneOf(District.class)),
    Eslov("Eslöv",EnumSet.noneOf(District.class)),
            Fagersta("Fagersta",EnumSet.noneOf(District.class)),
    Falkenberg("Falkenberg",EnumSet.noneOf(District.class)),
            Falkoping("Falköping",EnumSet.noneOf(District.class)),
    Falsterbo("Falsterbo",EnumSet.noneOf(District.class)),
            Falun("Falun",EnumSet.noneOf(District.class)),
    Filipstad("Filipstad",EnumSet.noneOf(District.class)),
            Flen("Flen",EnumSet.noneOf(District.class)),
    Gamla_Lodose("Gamla_Lodose",EnumSet.noneOf(District.class)),
    Getakarr("Getakarr",EnumSet.noneOf(District.class)),
            Granna("Gränna",EnumSet.noneOf(District.class)),
    Gavle("Gavle",EnumSet.noneOf(District.class)),
            Goteborg("Goteborg",EnumSet.noneOf(District.class)),
    Hagfors("Hagfors",EnumSet.noneOf(District.class)),
            Halmstad("Halmstad",EnumSet.noneOf(District.class)),
    Haparanda("Haparanda",EnumSet.noneOf(District.class)),
            Hedemora("Hedemora",EnumSet.noneOf(District.class)),
    Helsingborg("Helsingborg",EnumSet.noneOf(District.class)),
            Hjo("Hjo",EnumSet.noneOf(District.class)),
    Hudiksvall("Hudiksvall",EnumSet.noneOf(District.class)),
            Huskvarna("Huskvarna",EnumSet.noneOf(District.class)),
    Harnosand("Harnosand",EnumSet.noneOf(District.class)),
            Hassleholm("Hassleholm",EnumSet.noneOf(District.class)),
    Hoganas("Hoganas",EnumSet.noneOf(District.class)),
    Jarle("Jarle",EnumSet.noneOf(District.class)),
    Jonkoping("Jonkoping",EnumSet.noneOf(District.class)),
            Kalmar("Kalmar",EnumSet.noneOf(District.class)),
    Karl_Johans_stad("Karl_Johans_stad",EnumSet.noneOf(District.class)),
            Karlshamn("Karlshamn ",EnumSet.noneOf(District.class)),
    Karlskoga("Karlskoga",EnumSet.noneOf(District.class)),
            Karlskrona("Karlskrona",EnumSet.noneOf(District.class)),
    Karlstad("Karlstad",EnumSet.noneOf(District.class)),
            Katrineholm("Katrineholm",EnumSet.noneOf(District.class)),
    Kiruna("Kiruna",EnumSet.noneOf(District.class)),
            Kongahalla("Kongahalla",EnumSet.noneOf(District.class)),
    Kramfors("Kramfors",EnumSet.noneOf(District.class)),
            Kristianopel("Kristianopel",EnumSet.noneOf(District.class)),
    Kristianstad("Kristianstad",EnumSet.noneOf(District.class)),
            Kristinehamn("Kristinehamn",EnumSet.noneOf(District.class)),
    Kumla("Kumla",EnumSet.noneOf(District.class)),
            Kungsbacka("Kungsbacka",EnumSet.noneOf(District.class)),
    Kungalv("Kungalv",EnumSet.noneOf(District.class)),
            Koping("Koping",EnumSet.noneOf(District.class)),
    Laholm("Laholm",EnumSet.noneOf(District.class)),
            Landskrona("Landskrona",EnumSet.noneOf(District.class)),
    Lidingo("Lidingo",EnumSet.noneOf(District.class)),
            Lidkoping("Lidkoping",EnumSet.noneOf(District.class)),
    Lindesberg("Lindesberg",EnumSet.noneOf(District.class)),
            Linkoping("Linkoping",EnumSet.noneOf(District.class)),
    Ljungby("Ljungby",EnumSet.noneOf(District.class)),
            Lomma("Lomma",EnumSet.noneOf(District.class)),
    Ludvika("Ludvika",EnumSet.noneOf(District.class)),
            Lulea("Lulea",EnumSet.noneOf(District.class)),
    Lund("Lund",EnumSet.noneOf(District.class)),
            Luntertun("Luntertun",EnumSet.noneOf(District.class)),
    Lycksele("Lycksele",EnumSet.noneOf(District.class)),
            Lycka("Lycka",EnumSet.noneOf(District.class)),
    Lysekil("Lysekil",EnumSet.noneOf(District.class)),
            Lodose("Lodose",EnumSet.noneOf(District.class)),
    Malmo("Malmo",EnumSet.noneOf(District.class)),
            Mariefred("Mariefred",EnumSet.noneOf(District.class)),
    Mariestad("Mariestad",EnumSet.noneOf(District.class)),
            Marstrand("Marstrand",EnumSet.noneOf(District.class)),
    Mjolby("Mjolby",EnumSet.noneOf(District.class)),
            Motala("Motala",EnumSet.noneOf(District.class)),
    Molndal("Molndal",EnumSet.noneOf(District.class)),
            Monsteras("Monsteras",EnumSet.noneOf(District.class)),
    Nacka("Nacka",EnumSet.noneOf(District.class)),
            Nora("Nora",EnumSet.noneOf(District.class)),
    Norrkoping("Norrkoping",EnumSet.noneOf(District.class)),
            Norrtalje("Norrtalje",EnumSet.noneOf(District.class)),
    Nya_Lidkoping("Nya_Lidkoping",EnumSet.noneOf(District.class)),
    Nya_Lodose("Nya_Lodose",EnumSet.noneOf(District.class)),
    Nybro("Nybro",EnumSet.noneOf(District.class)),
            Nykoping("Nykoping",EnumSet.noneOf(District.class)),
    Nynashamn("Nynashamn",EnumSet.noneOf(District.class)),
            Nassjo("Nassjo",EnumSet.noneOf(District.class)),
    Oskarshamn("Oskarshamn",EnumSet.noneOf(District.class)),
            Oxelosund("Oxelosund",EnumSet.noneOf(District.class)),
    Pitea("Pitea",EnumSet.noneOf(District.class)),
            Ronneby("Ronneby",EnumSet.noneOf(District.class)),
    Sala("Sala",EnumSet.noneOf(District.class)),
            Sandviken("Sandviken",EnumSet.noneOf(District.class)),
    Sigtuna("Sigtuna",EnumSet.noneOf(District.class)),
            Simrishamn("Simrishamn",EnumSet.noneOf(District.class)),
    Skanor("Skanor",EnumSet.noneOf(District.class)),
    Skanor_med_Falsterbo("Skanor_med_Falsterbo",EnumSet.noneOf(District.class)),
            Skara("Skara",EnumSet.noneOf(District.class)),
    Skelleftea("Skelleftea",EnumSet.noneOf(District.class)),
            Skanninge("Skanninge",EnumSet.noneOf(District.class)),
    Skovde("Skovde",EnumSet.noneOf(District.class)),
    Solleftea("Solleftea",EnumSet.noneOf(District.class)),
    Solna("Solna",EnumSet.noneOf(District.class)),
    Stockholm("Stockholm",EnumSet.of(District.Sodermalm,District.Alvsjo,
            District.Bromma,District.Enskede_Arsta_Vantor,District.Farsta,
            District.Hagersten_Liljeholmen,District.Kungsholmen,District.Hasselby_Vallingby,
            District.Norrmalm,District.Rinkeby_Kista,District.Ostermalm,District.Skarholmen,
            District.Skarpnack,District.Spanga_Tensta)),
    Strangnas("Strangnas",EnumSet.noneOf(District.class)),
            Stromstad("Stromstad",EnumSet.noneOf(District.class)),
    Sundbyberg("Sundbyberg",EnumSet.noneOf(District.class)),
            Sundsvall("Sundsvall",EnumSet.noneOf(District.class)),
    Saffle("Säffle",EnumSet.noneOf(District.class)),
            Sater("Sater",EnumSet.noneOf(District.class)),
    Savsjo("Savsjo",EnumSet.noneOf(District.class)),
            Soderhamn("Soderhamn",EnumSet.noneOf(District.class)),
    Soderkoping("Soderkoping",EnumSet.noneOf(District.class)),
            Sodertalje("Sodertalje",EnumSet.noneOf(District.class)),
    Solvesborg("Solvesborg",EnumSet.noneOf(District.class)),
            Tidaholm("Tidaholm",EnumSet.noneOf(District.class)),
    Torget("Torget",EnumSet.noneOf(District.class)),
            Torshalla("Torshalla",EnumSet.noneOf(District.class)),
    Tranas("Tranås",EnumSet.noneOf(District.class)),
            Trelleborg("Trelleborg",EnumSet.noneOf(District.class)),
    Trollhattan("Trollhattan",EnumSet.noneOf(District.class)),
            Trosa("Trosa",EnumSet.noneOf(District.class)),
    Tumathorp("Tumathorp",EnumSet.noneOf(District.class)),
            Uddevalla("Uddevalla",EnumSet.noneOf(District.class)),
    Ulricehamn("Ulricehamn",EnumSet.noneOf(District.class)),
            Umea("Umea",EnumSet.noneOf(District.class)),
    Uppsala("Uppsala",EnumSet.noneOf(District.class)),
            Vadstena("Vadstena",EnumSet.noneOf(District.class)),
    Varberg("Varberg",EnumSet.noneOf(District.class)),
            Vaxholm("Vaxholm",EnumSet.noneOf(District.class)),
    Vetlanda("Vetlanda",EnumSet.noneOf(District.class)),
            Vimmerby("Vimmerby",EnumSet.noneOf(District.class)),
    Visby("Visby",EnumSet.noneOf(District.class)),
            Va("Va",EnumSet.noneOf(District.class)),
    Vanersborg("Vanersborg",EnumSet.noneOf(District.class)),
            Varnamo("Varnamo",EnumSet.noneOf(District.class)),
    Vastervik("Vastervik",EnumSet.noneOf(District.class)),
            Vasteras("Vasteras",EnumSet.noneOf(District.class)),
    Vaxjo("Vaxjo",EnumSet.noneOf(District.class)),
            Ystad("Ystad",EnumSet.noneOf(District.class)),
    Ahus("Åhus",EnumSet.noneOf(District.class)),
            Amal("Amal",EnumSet.noneOf(District.class)),
    Alvsborg("Älvsborg",EnumSet.noneOf(District.class)),
            Angelholm("Angelholm",EnumSet.noneOf(District.class)),
    Ojebyn("Ojebyn",EnumSet.noneOf(District.class)),
            Orebro("Orebro",EnumSet.noneOf(District.class)),
    Oregrund("Öregrund",EnumSet.noneOf(District.class)),
            Ornskoldsvik("Ornskoldsvik",EnumSet.noneOf(District.class)),
    Ostersund("Östersund",EnumSet.noneOf(District.class)),
            Osthammar("Östhammar",EnumSet.noneOf(District.class));



    private String name;
    private EnumSet<District> districts;

    City(String name,EnumSet<District> districts) {
        this.name = name;
        this.districts = districts;
    }

    public EnumSet<District> getDistricts() {
        return districts;
    }

    public String getName() {
        return name;
    }
}
