package com.itemstore.location.country.sweden;

import java.util.EnumSet;

public enum Region {

    BLEKINGE_LAN("Blekinge län",
            EnumSet.of(City.Ronneby, City.Solvesborg, City.Elleholm, City.Karlshamn,
            City.Karlskrona, City.Kristianopel, City.Lycka)),
    DALARNAS_LAN("Dalarnas län", EnumSet.of(City.Avesta,
            City.Borlange,
            City.Falun,
            City.Hedemora,
            City.Ludvika,
            City.Sater)),
    GOTLANDS_LAN("Gotlands län", EnumSet.of(City.Visby)),
    GAVLEBORGS_LAN("Gävleborgs län", EnumSet.of(City.Bollnas,
            City.Gavle,
            City.Hudiksvall,
            City.Sandviken,
            City.Soderhamn)),
    HALLANDS_LAN("Hallands län", EnumSet.of(City.Falkenberg,
            City.Getakarr,
            City.Halmstad,
            City.Kungsbacka,
            City.Laholm,
            City.Varberg)),
    JAMTLANDS_LAN("Jämtlands län", EnumSet.of(City.Ostersund)),
    JONKOPINGS_LAN("Jönköpings län", EnumSet.of(City.Eksjo,
            City.Granna,
            City.Huskvarna,
            City.Jonkoping,
            City.Nassjo,
            City.Savsjo,
            City.Tranas,
            City.Vetlanda,
            City.Varnamo)),

    KALMAR_LAN("Kalmar län", EnumSet.of(City.Borgholm,
            City.Kalmar,
            City.Monsteras,
            City.Nybro,
            City.Oskarshamn,
            City.Vimmerby,
            City.Vastervik)),

    KRONOBERGS_LAN("Kronobergs län", EnumSet.of( City.Ljungby,
            City.Torget,
            City.Vaxjo)),
    NORRBOTTENS_LAN("Norrbottens län", EnumSet.of( City.Boden,
            City.Haparanda,
            City.Karl_Johans_stad,
            City.Kiruna,
            City.Lulea,
            City.Pitea,
            City.Ojebyn)),
    SKANE_LAN("Skåne län", EnumSet.of(City.Bastad,
            City.Hassleholm,
            City.Kristianstad,
            City.Luntertun,
            City.Simrishamn,
            City.Tumathorp,
            City.Va,
            City.Ahus,
            City.Angelholm, City.Eslov,
            City.Falsterbo,
            City.Helsingborg,
            City.Hoganas,
            City.Landskrona,
            City.Lomma,
            City.Lund,
            City.Malmo,
            City.Skanor,
            City.Skanor_med_Falsterbo,
            City.Trelleborg,
            City.Ystad)),

    STOCKHOLMS_LAN("Stockholms län", EnumSet.of(City.Osthammar,City.Djursholm,
            City.Lidingo,
            City.Nacka,
            City.Norrtalje,
            City.Nynashamn,
            City.Sigtuna,
            City.Solna,
            City.Stockholm,
            City.Sundbyberg,
            City.Sodertalje,
            City.Vaxholm,
            City.Oregrund)),

    SODERMANLANDS_LAN("Södermanlands län", EnumSet.of(City.Eskilstuna,
            City.Flen,
            City.Katrineholm,
            City.Mariefred,
            City.Nykoping,
            City.Oxelosund,
            City.Strangnas,
            City.Torshalla,
            City.Trosa)),
    UPPSALA_LAN("Uppsala län", EnumSet.of(City.Enkoping,City.Uppsala)),

    VARMLANDS_LAN("Värmlands län", EnumSet.of(City.Arvika,
            City.Broo,
            City.Filipstad,
            City.Hagfors,
            City.Karlstad,
            City.Kristinehamn,
            City.Saffle)),

    VASTERBOTTENS_LAN("Västerbottens län", EnumSet.of(City.Lycksele,
            City.Skelleftea,
            City.Umea)),

    VASTERNORRLANDS_LAN("Västernorrlands län", EnumSet.of(City.Harnosand,
            City.Kramfors,
            City.Solleftea,
            City.Sundsvall,
            City.Ornskoldsvik)),
    VASTMANLANDS_LAN("Västmanlands län", EnumSet.of(City.ARBOGA,
            City.Fagersta,
            City.Koping,
            City.Sala,
            City.Vasteras)),

    // Älvsborgs län,Skaraborgs län
    VASTRA_GOTALANDS_LAN("Västra Götalands län",
            EnumSet.of(City.Falkoping,
                    City.Hjo,
                    City.Lidkoping,
                    City.Mariestad,
                    City.Nya_Lidkoping,
                    City.Skara,
                    City.Lodose,
                    City.Skovde,
                    City.Tidaholm,
                    City.Goteborg,
            City.Kongahalla,
            City.Kungalv,
            City.Lysekil,
            City.Marstrand,
            City.Molndal,
            City.Stromstad,
            City.Uddevalla,
            City.Alvsborg,City.ALINGSAS,
            City.Boras,
            City.Bratte,
            City.Gamla_Lodose,
            City.Nya_Lodose,
            City.Trollhattan,
            City.Ulricehamn,
            City.Vanersborg,
            City.Amal)),

    OREBRO_LAN("Örebro län", EnumSet.of(City.Askersund,
            City.Jarle,
            City.Karlskoga,
            City.Kumla,
            City.Lindesberg,
            City.Nora,
            City.Orebro)),
    OSTERGOTLANDS_LAN("Östergötlands län", EnumSet.of(City.Linkoping,City.Mjolby,
            City.Motala,
            City.Norrkoping,
            City.Skanninge,
            City.Soderkoping,
            City.Vadstena));

    private String name;
    private EnumSet<City> cities;

    Region(String name, EnumSet<City> cities) {
        this.name = name;
        this.cities = cities;
    }

    public String getName() {
        return name;
    }

    public EnumSet<City> getCities() {
        return cities;
    }
}
